replicaCount: 1
image:
  repository: eoepca/eoepca-portal
  pullPolicy: IfNotPresent
  tag: "demo"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: eoepca-portal.demo.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: eoepca-portal-tls-certificate
      hosts:
        - eoepca-portal.demo.eoepca.org
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
configMap:
  auth_server_url: "https://identity.keycloak.develop.eoepca.org"
  identity_url: "master"
  realm: "eoepca-portal"
  client_id: "eoepca-portal"
  identity_api_url: "https://identity.api.develop.eoepca.org"
  ades_url: "https://ades.develop.eoepca.org/ogc-api/processes"
  resource_catalogue_url: "https://resource-catalogue.develop.eoepca.org"
  data_access_url: "https://data-access.develop.eoepca.org"
  workspace_url: "https://workspace-api.develop.eoepca.org"
  workspace_docs_url: "https://workspace-api.develop.eoepca.org/docs#"
  images_registry_url: "https://harbor.develop.eoepca.org"
  dummy_service_url: "https://identity.dummy-service.develop.eoepca.org"
  access_token_name: "auth_user_id"
  access_token_domain: ".develop.eoepca.org"
  refresh_token_name: "auth_refresh_token"
  refresh_token_domain: ".develop.eoepca.org"