nameOverride: ""
fullnameOverride: ""
kubeVersionOverride: ""
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  automountServiceAccountToken: false
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: false
    # fsGroup: 2000
  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # runAsUser: 1000
  extraArgs: []
  # - --foo
  # - --bar
  extraEnvVars: []
  # - name: FOO
  #   value: BAR
  extraVolumes: []
  # - emptyDir: {}
  #   name: tmp
  extraVolumeMounts: []
  # - mountPath: /tmp
  #   name: tmp
  priorityClassName: ""
  hostAliases: []
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"
  # - ip: "10.1.2.3"
  #   hostnames:
  #   - "foo.remote"
  #   - "bar.remote"
  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe:
    enabled: false
    httpGet:
      path: /oauth/health
      port: admin
  readinessProbe:
    enabled: true
    httpGet:
      path: /oauth/health
      port: admin
service:
  type: ClusterIP
  annotations: {}
  proxy:
    port: 3000
    nodePort:
  admin:
    port: 4000
    nodePort:
serviceAccount:
  create: true
  annotations: {}
  name: ""
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: identity.api-gatekeeper.demo.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: identity-api-gatekeeper-tls-certificate
      hosts:
        - identity.gatekeeper.demo.eoepca.org
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80
pdb:
  create: false
  minAvailable: 1
metrics:
  addPrometheusScrapeAnnotation: false
  serviceMonitor:
    enabled: false
    namespace: um
    additionalLabels: {}
    annotations: {}
    interval:
config:
    client-id: identity-api
    discovery-url: https://identity.keycloak.demo.eoepca.org/realms/master
    no-redirects: true
    no-proxy: true
    enable-uma: true
    cookie-domain: demo.eoepca.org
    cookie-access-name: auth_user_id
    cookie-refresh-name: auth_refresh_token
    enable-metrics: true
    enable-logging: true
    enable-request-id: true
    enable-login-handler: true
    enable-refresh-tokens: true
    enable-logout-redirect: true
    listen: :3000
    listen-admin: :4000
secrets:
    clientSecret: AgCdwW4KsLE3XRC7Fs06yX++XiGq/m0hRRiskgD8X04I8S32wZA+K9xmKcZ4jZMYMshVHd+TMWmg/dh/TcjOVyaqBbOb7dmDLAH8M80zwbjJCIUwlm7yGj0AGq/NlTkTywQHMopgqmQtUDCaDA+u578XrVEBD4h1p5BtwkIkki5SH8lQ8oESJIbYMVoGXzVeOi3Ni+n/Xai7KpxajOofhSRC7rJu9O9MtLrIazBrJwe9sQZdQ05NmLnkyxK3DQVpKv8HazBw2V6XyepQbkeVHqnocNzW650T+ML8ZGdST2eJAbLsvvIxJJTcf97msd8EmP4THYSauuvHFCCBE2hr3wjmMj7yjEC6soslVpi0pXVjfzgQSbrJ6DcGGbcS+SBg7gc6vsgtUwOXnEElUjNWc6S0wdmstPrHk5DRjSVXw5BaN7+MLVT2WxY4X+O0ovtblcDMW4UwqT/kfMi0VQIZUYLPOpI8uoTxjv2WFIZ2wKKeXuW8p2ZIslVMbefSXK0UKx6mwKuw4srO3DvbM2kYeNDXlwRMRbwCQ4Yv+ZLFPjvabfZPNdYIhx9F8tXwtOzJ5saMKGfk6Cg9DyAsYtH7SQmhmc3sabS212YpgLWoLgJ694+ciYqLgAJT4CCobbD0yJbIOO1Mrw9ovUPrl6lwyaE98ouBfgUXxMOddQ4HukbT4+bmxEvsQZZLBY47nKcuBv3aE4qoezZsorqlOV4+y2cUgpIYZdBwnBSFFwvJwlu6KQ==
    encryptionKey: AgBuyRyCPZRklYT/hq5AXi+P6//IwYJsc15vAqjZHsS2Gwj3XzoTrQZ+QbFHDHcZKOwuUY8Nf4v6uH4HKOBd2HbSLvjoXNqPu6BfTFrT/V8VApaLGH4WVpwZvD+cfyscbpO8/vlctaJAq14RWAh+U8zgwY9sX0O9hwDBYn3wXGiGmgBhhhUafeTdZdZi/4+hSGuEzdeJq2wMMZNroM4CwZPLn9VHzquM4V4/bJGrGJbkH31nX6HZNy9ZhJenYPRY2jzREYX+r0R7utoYjPxZmz7Jppe5UcHJs4cxu4NE5zUS6lXavhgftR8U9D6vnC7/bRXp/fVCBvUeVR28EUcoa7ZU9fljKNIwEExFOHoARs814WU1ZJFMpjouMznXLyNs2leIG5qmZjTJpcrQpfsD1r7W/8DjPfeoznElUH8PjRIxzyDTkQdqDhpPsD6JAGVzEpt9sAXCMqbEjNxCRtmEbUvzSbcOvzQBchH/4GN6OFzGWH4pjHdCuxPaHVdxr0EodV6XSb/+ej1x/62+70W9cNpDz4y6KIizomcJPbj8Nc1NGDZ1YUKYnKgnMmDfykYXsJ9qAjJNXjVGEyhrF7V8/ec4dm+5Pl+aDIIn0ASyFLk0NrFLkMG8iryMtjTrbC2rvT0u0Mzsecf3kbtSv7TwUHhwTGszUgb3vN0xNZzTfM4op4pM+d0nO2kaJGBYJkvNOlxVb6AUWzfvyZdNlJ4/YDRJ8mawd195AL0VCcD6f1K6cQ==