apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pdp-{{ .Values.context }}-service
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: {{ .Values.global.ingressPath }}(/|$)(.*)
        backend:
          serviceName: {{ .Values.global.pdp }}
          servicePort: {{ .Values.global.port }}