apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.pdp }}-cm
data:
  PDP_AUTH_SERVER_URL: https://{{ .Values.global.domain | quote }}
  PDP_PREFIX: {{ .Values.global.prefix | quote }}
  PDP_HOST: {{ .Values.global.host | quote }}
  PDP_PORT: {{ .Values.global.port | quote }}
  PDP_CHECK_SSL_CERTS: {{ .Values.configMap.check_ssl_certs | quote }}
  PDP_DEBUG_MODE: {{ .Values.configMap.debug_mode | quote }}
