apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.pdp }}
  labels:
    app: {{ .Values.global.pdp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.pdp }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.pdp }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      containers:
      - name: {{ .Values.global.pdp }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.requests.serviceMemory }}
            cpu: {{ .Values.requests.serviceCpu }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.global.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.global.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        ports:
        {{- range $key, $value := .Values.ports }}
        - containerPort: {{ $value.targetPort }}
          name: {{ $key }}
          protocol: {{ $value.type }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.global.pdp }}-cm
      - name: mongo
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: mongo
        resources:
          requests:
            memory: {{ .Values.requests.dbMemory }}
            cpu: {{ .Values.requests.dbCpu }}
        ports:
        - name: http-rp
          containerPort: 27017
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.global.pdp }}-cm
        volumeMounts:
        - mountPath: /data/db/
          subPath: {{ .Values.global.pdp }}/data/db
          name: vol-userman
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}