apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rm-workspace-api.fullname" . }}
rules:
  - apiGroups: [""]
    verbs: ["get", "watch", "patch", "create", "delete"]
    resources:
      - secrets
  - apiGroups: ["epca.eo"]
    verbs: ["get", "watch", "patch", "create", "delete"]
    resources:
      - workspaces
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources:
      - namespaces
  - apiGroups: ["networking.k8s.io"]
    verbs: ["get", "list"]
    resources:
      - ingresses
  - apiGroups: ["apisix.apache.org"]
    verbs: ["get", "list"]
    resources:
      - apisixroutes