kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rm-workspace-api.fullname" . }}
  labels:
    {{- include "rm-workspace-api.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rm-workspace-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "rm-workspace-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io