---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: pep-engine
  annotations:
    {{- if .Values.global.certManager.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.certManager.clusterIssuer }}
    {{- end }}
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  {{- if eq .Values.configMap.workingMode "PARTIAL" }}
  - host: {{ printf "%s-pep.%s" .Values.global.context .Values.global.domain | quote }}
  {{- else }}
  - host: {{ printf "%s.%s" .Values.global.context .Values.global.domain | quote }}
  {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: "ImplementationSpecific"
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ (tpl .Values.global.pep $) }}
            port:
              number: {{ index .Values "global" "ports" "proxy-pep" "port" }}
          {{- else }}
          serviceName: {{ (tpl .Values.global.pep $) }}
          servicePort: {{ index .Values "global" "ports" "proxy-pep" "port" }}
          {{- end }}
  {{- if .Values.global.certManager.clusterIssuer }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.global.context .Values.global.domain | quote }}
      secretName: pep-tls-certificate
  {{- end }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.global.context }}-pepapi
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - host: {{ printf "%s-pepapi.%s" .Values.global.context .Values.global.domain | quote }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: "ImplementationSpecific"
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ (tpl .Values.global.pep $) }}
            port:
              number: {{ index .Values "global" "ports" "resources-pep" "port" }}
          {{- else }}
          serviceName: {{ (tpl .Values.global.pep $) }}
          servicePort: {{ index .Values "global" "ports" "resources-pep" "port" }}
          {{- end }}
---
{{- if and (eq .Values.configMap.workingMode "PARTIAL") (.Values.nginxIntegration.enabled) }}
{{- $defaultHostname := default (include "pep-engine.fullname" .) .Values.global.context }}
{{- $hostname := default $defaultHostname .Values.nginxIntegration.hostname }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $hostname }}
  annotations:
    {{- if .Values.global.certManager.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.certManager.clusterIssuer }}
    {{- end }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request /authcheck;
    nginx.ingress.kubernetes.io/server-snippet: |
      location /authcheck {
        internal;
        set $pep_address {{ (tpl .Values.global.pep $) }}.{{ .Release.Namespace }}.{{ .Values.global.clusterDomain }}:{{ index .Values "global" "ports" "proxy-pep" "port" }};
        proxy_pass http://$pep_address/authorize;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
      }
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ printf "%s.%s" $hostname .Values.global.domain | quote }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: "ImplementationSpecific"
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ (tpl .Values.global.resourceServer.name $) }}
            port:
              number: {{ .Values.global.resourceServer.port }}
          {{- else }}
          serviceName: {{ (tpl .Values.global.resourceServer.name $) }}
          servicePort: {{ .Values.global.resourceServer.port }}
          {{- end }}
  {{- if .Values.global.certManager.clusterIssuer }}
  tls:
    - hosts:
        - {{ printf "%s.%s" $hostname .Values.global.domain | quote }}
      secretName: {{ printf "%s-tls" $hostname | quote }}
  {{- end }}
{{- end }}