---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-service
  
  annotations:
    {{- if .Values.certManager.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuer }}
    {{- end }}
    {{- if .Values.elbIp }}
    kubernetes.io/elb.ip: {{ .Values.elbIp }}
    {{- else }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
spec:
  rules:
  - host: {{ printf "%s.%s" .Values.context .Values.global.domain | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.global.pep }}
          servicePort: {{ .Values.global.proxyServicePort }}
  {{- if .Values.certManager.clusterIssuer }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.context .Values.global.domain | quote }}
      secretName: {{ printf "%s-pep-tls" .Values.context | quote }}
  {{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-resources
  
  annotations:
    {{- if .Values.elbIp }}
    kubernetes.io/elb.ip: {{ .Values.elbIp }}
    {{- else }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
spec:
  rules:
  - host: {{ printf "%s-pepapi.%s" .Values.context .Values.global.domain | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.global.pep }}
          servicePort: {{ .Values.global.resourcesServicePort }}
