apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (tpl .Values.global.pep $) }}-cm
data:
  PEP_REALM: {{ .Values.global.realm | quote }}
  PEP_AUTH_SERVER_URL: {{ printf "https://%s.%s" .Values.configMap.asHostname .Values.global.domain }}
  PEP_SERVICE_HOST: {{ .Values.global.serviceHost | quote }}
  PEP_SERVICE_PORT: {{ index .Values "global" "ports" "proxy-pep" "port" | quote }}
  PEP_S_MARGIN_RPT_VALID: {{ .Values.configMap.margin | quote }}
  PEP_CHECK_SSL_CERTS: {{ .Values.configMap.sslCerts | quote }}
  PEP_USE_THREADS: {{ .Values.configMap.useThreads | quote }}
  PEP_DEBUG_MODE: {{ .Values.configMap.debugMode | quote }}
  PEP_RESOURCE_SERVER_ENDPOINT: {{ .Values.global.resourceServer.url | default (printf "http://%v:%v/" (tpl .Values.global.resourceServer.name $) .Values.global.resourceServer.port) | quote }}
  PEP_API_RPT_UMA_VALIDATION: {{ .Values.configMap.umaValidation | quote }}
  PEP_RPT_LIMIT_USES: {{ .Values.configMap.limitUses | quote }}
  PEP_PDP_URL: {{ printf "http://%s.%s" .Values.configMap.pdpHostname .Values.global.domain }}
  PEP_PDP_PORT: {{ .Values.configMap.pdpPort | quote }}
  PEP_PDP_POLICY_ENDPOINT: {{ .Values.configMap.pdpPolicy | quote }}
  PEP_VERIFY_SIGNATURE: {{ .Values.configMap.verifySignature | quote }}
  PEP_PROXY_SERVICE_PORT: {{ index .Values "global" "ports" "proxy-pep" "port" | quote }}
  PEP_RESOURCES_SERVICE_PORT: {{ index .Values "global" "ports" "resources-pep" "port" | quote }}
  PEP_DEFAULT_RESOURCE_PATH: {{ .Values.configMap.defaultResourcePath | quote }}
  PEP_WORKING_MODE: {{ .Values.configMap.workingMode | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (tpl .Values.global.pep $) }}-custom-resources
data:
  {{- if or .Values.defaultResources .Values.customDefaultResources }}
  {{- $resources := list }}
  {{- range .Values.defaultResources }}
    {{- $resources = append $resources . }}
  {{- end}}
  {{- range .Values.customDefaultResources }}
    {{- $resources = append $resources . }}
  {{- end}}
  default-resources.json: |
    {
      "default_resources": [
        {{- range $i, $v := $resources }}
          {{- if not (eq $i 0) }},{{- end }}
          {{- $v | toPrettyJson | nindent 8 }}
        {{- end }}
      ]
    }
  {{- else }}
  {{ fail "default resources must be supplied" }}
  {{- end }}
