apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.pep }}-cm
data:
  PEP_REALM: {{ .Values.global.realm | quote }}
  PEP_AUTH_SERVER_URL: https://{{ .Values.global.domain }}
  PEP_SERVICE_HOST: {{ .Values.global.serviceHost | quote }}
  PEP_SERVICE_PORT: {{ .Values.global.proxyServicePort | quote }}
  PEP_S_MARGIN_RPT_VALID: {{ .Values.configMap.margin | quote }}
  PEP_CHECK_SSL_CERTS: {{ .Values.configMap.sslCerts | quote }}
  PEP_USE_THREADS: {{ .Values.configMap.useThreads | quote }}
  PEP_DEBUG_MODE: {{ .Values.configMap.debugMode | quote }}
  PEP_RESOURCE_SERVER_ENDPOINT: {{ .Values.configMap.resourceServer | quote }}
  PEP_API_RPT_UMA_VALIDATION: {{ .Values.configMap.umaValidation | quote }}
  PEP_RPT_LIMIT_USES: {{ .Values.configMap.limitUses | quote }}
  PEP_PDP_URL: http://{{ .Values.global.domain }}
  PEP_PDP_PORT: {{ .Values.configMap.pdpPort | quote }}
  PEP_PDP_POLICY_ENDPOINT: {{ .Values.configMap.pdpPolicy | quote }}
  PEP_VERIFY_SIGNATURE: {{ .Values.configMap.verifySignature | quote }}
  PEP_PROXY_SERVICE_PORT: {{ .Values.global.proxyServicePort | quote }}
  PEP_RESOURCES_SERVICE_PORT: {{ .Values.global.resourcesServicePort | quote }}
  PEP_DEFAULT_RESOURCE_PATH: {{ .Values.configMap.defaultResourcePath | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-resources  
data:
  {{ if .Files.Get "scripts/default-resources.json" }}
  default-resources.json: {{ .Files.Get "scripts/default-resources.json" | quote  }}
  {{ else }}
  {{ fail "you need to supply a default resource JSON file! add 'default-resources.json' to your chart 'scripts' directory." }}
  {{ end }}