apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.pep }}
  labels:
    app: {{ .Values.global.pep }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.pep }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.pep }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.global.pep }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: {{ .Values.requests.serviceMemory }}
            cpu: {{ .Values.requests.serviceCpu }}
        livenessProbe:
          tcpSocket:
            port: {{ index .Values "global" "ports" "proxy-pep" "port" }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ index .Values "global" "ports" "proxy-pep" "port" }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        ports:
        {{- range $key, $value := .Values.global.ports }}
        - containerPort: {{ $value.targetPort }}
          name: {{ $key }}
          protocol: {{ $value.type }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.global.pep }}-cm
        volumeMounts:
        - name: default-resources
          mountPath: /data/
      - name: mongo
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: mongo
        resources:
          requests:
            memory: {{ .Values.requests.dbMemory }}
            cpu: {{ .Values.requests.dbCpu }}
        ports:
        - name: http-rp
          containerPort: 27017
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.global.pep }}-cm
        volumeMounts:
        - mountPath: /data/db/
          subPath: {{ .Values.global.pep }}/{{ .Values.global.context }}/data/db
          name: {{ .Values.volumeClaim.name }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ printf "%s.%s" .Values.configMap.asHostname .Values.global.domain }}
        {{- if not (eq .Values.configMap.asHostname .Values.configMap.pdpHostname) }}
        - {{ printf "%s.%s" .Values.configMap.pdpHostname .Values.global.domain }}
        {{- end }}
      volumes:
        - name: {{ .Values.volumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: default-resources
          configMap:
            name: {{ .Values.global.pep }}-custom-resources