apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.pep }}
  labels:
    app: {{ .Values.global.pep }}
spec:
  ports:
    {{- range $key, $value := .Values.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.type }}
      name: {{ $key }}
    {{- end }}
  selector:
    app: {{ .Values.global.pep }}