apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.pep }}-cm
data:
  PEP_REALM: {{ .Values.global.realm | quote }}
  PEP_AUTH_SERVER_URL: {{ printf "https://%s.%s" .Values.configMap.asHostname .Values.global.domain }}
  PEP_SERVICE_HOST: {{ .Values.global.serviceHost | quote }}
  PEP_SERVICE_PORT: {{ index .Values "global" "ports" "proxy-pep" "port" | quote }}
  PEP_S_MARGIN_RPT_VALID: {{ .Values.configMap.margin | quote }}
  PEP_CHECK_SSL_CERTS: {{ .Values.configMap.sslCerts | quote }}
  PEP_USE_THREADS: {{ .Values.configMap.useThreads | quote }}
  PEP_DEBUG_MODE: {{ .Values.configMap.debugMode | quote }}
  PEP_RESOURCE_SERVER_ENDPOINT: {{ .Values.global.resourceServer.url | default (printf "http://%v:%v/" .Values.global.resourceServer.name .Values.global.resourceServer.port) | quote }}
  PEP_API_RPT_UMA_VALIDATION: {{ .Values.configMap.umaValidation | quote }}
  PEP_RPT_LIMIT_USES: {{ .Values.configMap.limitUses | quote }}
  PEP_PDP_URL: {{ printf "http://%s.%s" .Values.configMap.pdpHostname .Values.global.domain }}
  PEP_PDP_PORT: {{ .Values.configMap.pdpPort | quote }}
  PEP_PDP_POLICY_ENDPOINT: {{ .Values.configMap.pdpPolicy | quote }}
  PEP_VERIFY_SIGNATURE: {{ .Values.configMap.verifySignature | quote }}
  PEP_PROXY_SERVICE_PORT: {{ index .Values "global" "ports" "proxy-pep" "port" | quote }}
  PEP_RESOURCES_SERVICE_PORT: {{ index .Values "global" "ports" "resources-pep" "port" | quote }}
  PEP_DEFAULT_RESOURCE_PATH: {{ .Values.configMap.defaultResourcePath | quote }}
  PEP_WORKING_MODE: {{ .Values.configMap.workingMode | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.pep }}-custom-resources
data:
  {{ if .Files.Get "scripts/default-resources.json" }}
  default-resources.json: {{ .Files.Get "scripts/default-resources.json" | quote  }}
  {{ else }}
  {{ fail "you need to supply a default resource JSON file! add 'default-resources.json' to your chart 'scripts' directory." }}
  {{ end }}
