# Default values for pdp-engine.

global:
  namespace: default
  domain:  demoexample.gluu.org
  pdp: pdp-engine
  prefix: /
  host: 0.0.0.0
  port: 5567
  nginxIp: 10.0.2.15
  ingressPath: /pdp

ports:
  http-pdp:
    port: 5567
    targetPort: 5567
    type: TCP
  https-pdp:
    port: 1025
    targetPort: 443
    type: TCP

configMap:
  check_ssl_certs: "'false'"
  debug_mode: "'true'"

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 90
livenessProbe:
  initialDelaySeconds: 1
  periodSeconds: 90

requests:
  serviceCpu: 4m
  serviceMemory: 70Mi
  dbCpu: 2m
  dbMemory: 70Mi

image: 
  imagePullPolicy: IfNotPresent
  image: eoepca/um-pdp-engine:v1.0.1-RC
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

# VolumeClaim values
volumeClaim:
  name: um-pdp-engine-pvc
  create: true

context: generic
