{{- if and (.Values.secrets.clientSecret) (.Values.secrets.encryptionKey) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "identity-gatekeeper.fullname" . }}
  labels:
    {{- include "identity-gatekeeper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  PROXY_CLIENT_SECRET: "{{ .Values.secrets.clientSecret | b64enc }}"
  PROXY_ENCRYPTION_KEY: "{{ .Values.secrets.encryptionKey | b64enc }}"
{{- end }}