vs:
  global:
    env:
      COLLECTION: COLLECTION
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .TIF,.tif,.xml,.jp2
      GDAL_DISABLE_READDIR_ON_OPEN: "TRUE"
      COLLECT_STATIC: "false"
      AWS_VIRTUAL_HOSTING: "FALSE"
      AWS_S3_ENDPOINT: cf2.cloudferro.com:8080
      AWS_HTTPS: "YES"
      REGISTRAR_REPLACE: "true"
      REDIS_REGISTER_QUEUE_KEY: "register_queue"
      REDIS_REGISTER_PATH_QUEUE_KEY: "register_path_queue"
    storage:
      data:
        data:
          type: S3
          endpoint_url: https://cf2.cloudferro.com:8080
          region: RegionOne
          validate_bucket_name: False
      cache:
        type: local
        # type: S3
        # endpoint_url: "http://data.cloudferro.com"
        # access_key_id: access
        # secret_access_key: access
        # region: RegionOne
    metadata:
      title: EOEPCA Data Access View Server Client
      header: "EOEPCA Data Access View Server (VS) Client powered by <a href=\"//eox.at\"><img src=\"//eox.at/wp-content/uploads/2017/09/EOX_Logo.svg\" alt=\"EOX\" style=\"height:25px;margin-left:10px\"/></a>"

    layers: []

  renderer:
    image:
      repository: eoepca/rm-data-access-core
      tag: 1.1.0

  registrar:
    image:
      repository: eoepca/rm-data-access-core
      tag: 1.1.0
    config:
      disableDefaultEoxserver: true
      backends: []
        # will be filled by workspace API
        # - path: registrar_pycsw.backend.PycswBackend
        #   kwargs:
        #     repository_database_uri: postgresql://postgres:mypass@resource-catalogue-db/pycsw
        #     ows_url: https://data-access.demo.eoepca.org/ows

      pathBackends: []
        # will be filled by workspace API
        # - path: registrar_pycsw.backend.PycswCWLBackend
        #   kwargs:
        #     repository_database_uri: postgresql://postgres:mypass@resource-catalogue-db/pycsw
        #     ows_url: https://data-access.demo.eoepca.org/ows

  database:
    persistence:
      enabled: true
      existingClaim: data-access-db

  preprocessor:
    replicaCount: 0

  ingestor:
    replicaCount: 0

  harvester:
    image:
      repository: eoepca/rm-harvester
      tag: 1.0.0
    config:
      redis:
        host: data-access-redis-master
        port: 6379
      harvesters:
        - name: harvest-bucket-catalog
          resource:
            type: STACCatalog
            source:
              endpoint_url: https://cf2.cloudferro.com:8080
              validate_bucket_name: False
              region_name: RegionOne
              public: False

  cache:
    ingress:
      enabled: false

  client:
    ingress:
      enabled: false

  redis:
    usePassword: false
    persistence:
      existingClaim: data-access-redis
    master:
      persistence:
        enabled: true
        storageClass: managed-nfs-storage
    cluster:
      enabled: false

rm-resource-catalogue:
  ingress:
    enabled: false
    host: resource-catalogue.user.185.52.193.87.nip.io
    tls_host: resource-catalogue.user.185.52.193.87.nip.io
    tls_secret_name: resource-catalogue-user-tls
  pycsw:
    config:
      server:
        url: https://resource-catalogue.user.185.52.193.87.nip.io/
        federatedcatalogues: https://resource-catalogue.185.52.193.87.nip.io/

storage:
  storageClassName: managed-nfs-storage
