# Default values for login-service.
imagePullSecrets: []

global:
  nginxIp: 10.0.2.15
  domain: demoexample.gluu.org
  serviceHost: 0.0.0.0
  servicePort: 5566
  user: user-profile
  baseUri: "/web_ui"

ports:
  http-up:
    port: 5566
    targetPort: 5566
    type: TCP
  https-up:
    port: 1028
    targetPort: 443
    type: TCP

configMap:
  title: "EOEPCA User Profile"
  scopes: "openid email user_name"
  redirectUri: "/web_ui/oauth/callback"
  postLogoutRedirectUri: "/web_ui"
  oauthCallbackPath: "/oauth/callback"
  logoutEndpoint: "/logout"
  protectedAttributes: "userName active emails displayName value primary"
  blacklistAttributes: "schemas id meta $ref"
  separatorUiAttributes: "->"
  colorWebBackground: "#D7EDEC"
  colorWebHeader: "#FFFFFF"
  logoAltName: "EOEPCA Logo"
  logoImagePath: "/static/img/logo.png"
  colorHeaderTable: "#38A79F"
  colorTextHeaderTable: "white"
  colorButtonModify: "#38A79F"
  useThreads: "true"
  debugMode: "true"


image: 
  repository: eoepca/um-user-profile
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

# VolumeClaim values
volumeClaim:
  name: um-user-profile-pvc
  create: true

readinessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90
livenessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90

requests:
  memory: 70Mi
  cpu: 3m

context: user
