apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-postgres.name" . }}-secret
  labels:
    {{- include "identity-postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: "{{ .Values.configMap.postgresDb }}"
  POSTGRES_USER: "{{ .Values.configMap.postgresUser }}"
  PGDATA: "{{ .Values.configMap.pgData }}"