apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-postgres.name" . }}
  labels:
    {{- include "identity-postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "identity-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "identity-postgres.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity-postgres.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          args:
            {{- toYaml .Values.deployment.args | nindent 12 }}
          env:
            {{- with .Values.deployment.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.deployment.extraEnvFrom }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
            - configMapRef:
                name: {{ include "identity-postgres.name" . }}-secret
            - secretRef:
                name: {{ include "identity-postgres.name" . }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          volumeMounts:
            - mountPath: {{ .Values.deployment.volumeMountPath }}
              name: {{ .Values.deployment.volumeMountName }}
          #
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          #
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          #
          {{- with .Values.deployment.startupProbe }}
          startupProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.deployment.volumeMountName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}