{{- if and (.Values.secrets.postgresPassword) (.Values.secrets.pgPassword) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "identity-postgres.name" . }}
  labels:
    {{- include "identity-postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword | b64enc }}"
  PGPASSWORD: "{{ .Values.secrets.pgPassword | b64enc }}"
{{- end }}