apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-postgres.name" . }}
  labels:
    {{- include "identity-postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "identity-postgres.selectorLabels" . | nindent 4 }}