# Default values for pep-engine.
imagePullSecrets: []

global:
  # The context is used to distinguish PEP instances,
  # e.g. PEP for ADES vs PEP for Catalogue etc.
  context: generic
  namespace: default
  pep: pep-engine
  # Domain of the Kubernetes cluster
  clusterDomain: svc.cluster.local
  # DNS domain of the deployment
  domain: myplatform.eoepca.org
  realm: eoepca
  serviceHost: 0.0.0.0
  ports:
    proxy-pep:
      port: 5566
      targetPort: 5566
      type: TCP
    resources-pep:
      port: 5576
      targetPort: 5576
      type: TCP
  nginxIp: 10.0.2.15
  resourceServer:
    name: myservice
    port: 80
    # resourceServer.url is derived from the name and port, but can be overriden here
    # url: http://<name>:<port>/
  # Add TLS certs.
  # Empty value for `clusterIssuer` disables
  certManager:
    clusterIssuer: ""

configMap:
  margin: 5
  sslCerts: "'false'"
  useThreads: "'true'"
  debugMode: "'true'"
  umaValidation: "'true'"
  limitUses: 100
  asHostname: "auth" # Authorization Server: Just the hostname part. Will be pre-pended to the `global.domain` for the FQDN
  pdpHostname: "pdp" # PDP: Just the hostname part. Will be pre-pended to the `global.domain` for the FQDN
  pdpPort: 5567
  pdpPolicy: /pdp/policy/
  verifySignature: "'false'"
  defaultResourcePath: /data/default-resources.json
  workingMode: "PARTIAL"

# Default resources to apply for initial protection
# This protects the base path with `public_access` under the
# ownership of an operator
defaultResources:
  - name: "Base Path"
    description: "Base path for Open Access to service"
    resource_uri: "/"
    scopes:
      - "public_access"
    default_owner: "0000000000000"

# Additional (custom) default resources - designed to be supplied
# for specific deployment policies.
# A separate value from `defaultResources` is used to avoid inadvertently
# overwriting the default policy.
customDefaultResources: []

nginxIntegration:
  # Flag to create ingress with config for nginx auth_request
  enabled: false
  # First part of the hostname - global.domain will be appended
  hostname: ""

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 90
livenessProbe:
  initialDelaySeconds: 1
  periodSeconds: 90

requests:
  serviceCpu: 2m
  serviceMemory: 50Mi
  dbCpu: 3m
  dbMemory: 150Mi

image:
  statefulSetReplicas: 1
  repository: eoepca/um-pep-engine
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

# VolumeClaim values
volumeClaim:
  name: um-pep-engine-pvc
  create: true
