identity-postgres:
  enabled: true
  deployment:
    image:
      repository: postgres
      pullPolicy: IfNotPresent
identity-keycloak:
  enabled: true
  deployment:
    image:
      repository: quay.io/keycloak/keycloak
      pullPolicy: IfNotPresent
identity-api:
  enabled: true
  deployment:
    image:
      repository: ghcr.io/eoepca/um-identity-api
      pullPolicy: IfNotPresent
identity-api-gatekeeper:
  enabled: true
  fullnameOverride: identity-api-protection
  config:
    client-id: identity-api
    discovery-url: https://identity.keycloak.myplatform.mydomain/realms/master
    cookie-domain: myplatform.mydomain
  targetService:
    host: identity-api-protected.myplatform.mydomain
    name: identity-api
    port:
      number: 8080
  # Values for secret 'identity-api-protection'
  secrets:
    # Note - if ommitted, these can instead be set by creating the secret independently.
    clientSecret: "changeme"
    encryptionKey: "changemechangeme"
  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    openUri:
      - ^/(docs|openapi.json)
