apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-keycloak.name" . }}
  labels:
    {{- include "identity-keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_LOGLEVEL: "{{ .Values.configMap.keycloakLoglevel }}"
  WILDFLY_LOGLEVEL: "{{ .Values.configMap.wildflyLoglevel }}"
  KEYCLOAK_ADMIN: "{{ .Values.configMap.keycloakAdmin }}"
  KC_PROXY: "{{ .Values.configMap.kcProxy }}"
  KC_HOSTNAME_STRICT: "{{ .Values.configMap.kcHostnameStrict }}"
  KC_DB: "{{ .Values.configMap.kcDb }}"
  KC_DB_USERNAME: "{{ .Values.configMap.kcDbUsername }}"
  KC_DB_URL_HOST: "{{ .Values.configMap.kcDbUrlHost }}"
  KC_DB_URL_PORT: "{{ .Values.configMap.kcDbUrlPort }}"