apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "identity-keycloak.name" . }}
  labels:
    {{- include "identity-keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    KC_DB_PASSWORD: "{{ .Values.secrets.kcDbPassword }}"
    KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.secrets.keycloakAdminPassword }}"