{{- if and (.Values.secrets.kcDbPassword) (.Values.secrets.keycloakAdminPassword) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "identity-keycloak.name" . }}
  labels:
    {{- include "identity-keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KC_DB_PASSWORD: "{{ .Values.secrets.kcDbPassword }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.secrets.keycloakAdminPassword }}"
{{- end }}