apiVersion: v1
kind: ConfigMap
metadata:
  name: um-pricing-engine-config
data:
  PRICING_AUTH_SERVER_URL: {{ .Values.global.auth_server_url | quote }}
  PRICING_PREFIX: {{ .Values.global.prefix | quote }}
  PRICING_HOST: {{ .Values.global.host | quote }}
  PRICING_PORT: {{ .Values.global.port | quote }}
  PRICING_CHECK_SSL_CERTS: {{ .Values.global.check_ssl_certs | quote }}
  PRICING_DEBUG_MODE: {{ .Values.global.debug_mode | quote }}
