apiVersion: v1
kind: ConfigMap
metadata:
  name: um-billing-service-config
data:
  BIS_AUTH_SERVER_URL: {{ .Values.global.auth_server_url | quote }}
  BIS_PREFIX: {{ .Values.global.prefix | quote }}
  BIS_HOST: {{ .Values.global.host | quote }}
  BIS_PORT: {{ .Values.global.port | quote }}
  BIS_CHECK_SSL_CERTS: {{ .Values.global.check_ssl_certs | quote }}
  BIS_DEBUG_MODE: {{ .Values.global.debug_mode | quote }}
