apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.bis }}
  labels:
    app: {{ .Values.global.bis }}
spec:
  type: NodePort
  ports:
  - port: 5569
    name: http-bis
    targetPort: 5569
    protocol: TCP
    nodePort: 31709
  - port: 1029
    name: https-bis
    targetPort: 443
    protocol: TCP
  selector:
    app: {{ .Values.global.bis }}