apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cheddar
  name: cheddar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheddar
  template:
    metadata:
      labels:
        app: cheddar
    spec:
      containers:
      - name: cheddar
        image: "{{ .Values.cheddar.image.repository }}:{{ .Values.cheddar.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.cheddar.image.pullPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stilton
  name: stilton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stilton
  template:
    metadata:
      labels:
        app: stilton
    spec:
      containers:
      - name: stilton
        image: "{{ .Values.stilton.image.repository }}:{{ .Values.stilton.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.stilton.image.pullPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wensleydale
  name: wensleydale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wensleydale
  template:
    metadata:
      labels:
        app: wensleydale
    spec:
      containers:
      - name: wensleydale
        image: "{{ .Values.wensleydale.image.repository }}:{{ .Values.wensleydale.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.wensleydale.image.pullPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cheddar
  name: cheddar
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: cheddar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stilton
  name: stilton
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: stilton
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wensleydale
  name: wensleydale
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: wensleydale
