apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rm-minio-bucket-api.fullname" . }}
  labels:
    {{- include "rm-minio-bucket-api.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "rm-minio-bucket-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rm-minio-bucket-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /probe
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /probe
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            - name: NAMESPACE_FOR_BUCKET_RESOURCE
              value: "{{ .Values.namespaceForBucketResource }}"
            - name: MINIO_SERVER_ENDPOINT
              value: "{{ .Values.minIOServerEndpoint }}"
            {{- if .Values.accessCredentials.secretName }}
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.accessCredentials.secretName }}"
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.accessCredentials.secretName }}"
                  key: rootPassword
            {{- else }}
            - name: MINIO_ROOT_USER
              value: "{{ .Values.accessCredentials.user }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.accessCredentials.password }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
