# Declare variables to be passed into your templates.
enabled: true
replicaCount: 1
dynamicStorage: true

image:
  repository: "{{ .Values.global.images.oxauth.repository }}"
  tag: "{{ .Values.global.images.oxauth.tag }}"
  pullPolicy: "{{ .Values.global.images.oxauth.pullPolicy }}"

falsure: "'false'"
#ConfigMap values
gluuLdapUrl: opendj:1636
gluuMaxRamFraction: 1

#Resources for the deployment
resources:
  requests:
    cpu: 200m
    memory: 1.2Gi
  limits: {}

#hostAliases
nginxIp: 10.0.2.15

#ports for the deployment
ports:
  containerPort: 8080

# livenessProbe
livenessProbe:
  initialDelaySeconds: 100
  periodSeconds: 60

# readinessProbe
readinessProbe:
  initialDelaySeconds: 100
  periodSeconds: 60

# VolumeClaim values
volumeClaim:
  name: um-login-service-oxauth-pvc
  storage: 50M

#VolumeMounts
volumeMounts:
  logs:
    mountPath: /opt/gluu/jetty/oxauth/logs
    subPath: oxauth/logs
  ext:
    mountPath: /opt/gluu/jetty/oxauth/lib/ext
    subPath: oxauth/lib/ext
  static:
    mountPath: /opt/gluu/jetty/oxauth/custom/static
    subPath: oxauth/custom/static
  pages:
    mountPath: /opt/gluu/jetty/oxauth/custom/pages
    subPath: oxauth/custom/pages

persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate