baseHostname: 192.168.49.2.nip.io

cheddar:
    image:
        repository: errm/cheese
        pullPolicy: IfNotPresent
        tag: cheddar
stilton:
    image:
        repository: errm/cheese
        pullPolicy: IfNotPresent
        tag: stilton
wensleydale:
    image:
        repository: errm/cheese
        pullPolicy: IfNotPresent
        tag: wensleydale

service:
    port: 80
