{{ if .Values.iam.keycloak.enabled -}}
{{ if .Values.iam.keycloak.postgres.enabled -}}
{{ if not .Values.iam.keycloak.postgres.secretRef -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
{{- if and (not .Values.iam.keycloak.postgres.password) .Values.iam.keycloak.configuration.useSecretGenerator }}
    secret-generator.v1.mittwald.de/autogenerate: password
{{- end }}
data:
  username: {{ .Values.iam.keycloak.postgres.username | default "keycloak" | b64enc | quote }}
{{- if or .Values.iam.keycloak.postgres.password }}
  password: {{ .Values.iam.keycloak.postgres.password | b64enc | quote }}
{{- else if not .Values.iam.keycloak.configuration.useSecretGenerator }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgresql") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  password: {{ (get $secretData "password") | default (randAlphaNum 32 | b64enc) | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}