apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-cm
data:
  OIDC_RP_SIGN_ALGO: {{ .Values.configmap.sign_algo }}

  OIDC_OP_AUTHORIZATION_ENDPOINT: {{ printf "https://%s.%s/oxauth/restv1/authorize" .Values.authHost .Values.domain }}
  OIDC_OP_TOKEN_ENDPOINT: {{ printf "https://%s.%s/oxauth/restv1/token" .Values.authHost .Values.domain }}
  OIDC_OP_USER_ENDPOINT: {{ printf "https://%s.%s/oxauth/restv1/userinfo" .Values.authHost .Values.domain }}
  OIDC_OP_JWKS_ENDPOINT: {{ printf "https://%s.%s/oxauth/restv1/jwks" .Values.authHost .Values.domain }}

  OIDC_TOKEN_USE_BASIC_AUTH: {{ .Values.configmap.use_basic_auth | quote }}
  TOKEN_ID_COOKIE: {{ .Values.configmap.token_id_cookie }}
  USER_PREFIX: {{ .Values.configmap.user_prefix }}
  HOSTNAME: {{ .Values.domain }}
  AUTHHOST: {{ .Values.authHost }}
  PORTALHOST: {{ .Values.portalHost }}