{{- $fullName := include "application-hub.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-rbac
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-hub
    namespace: {{  .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
