apiVersion: v1
kind: ConfigMap
metadata:
  name: bucket-operator
data:
  application.yaml: |-
    logging:
      level:
        root: INFO
        eoepca: DEBUG
    management:
      endpoints:
        web:
          exposure:
            include: info, health, prometheus
    k8s:
      namespace: {{ .Release.Namespace }}
      cluster: eoepca