apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.epca.eo
spec:
  conversion:
    strategy: None
  group: epca.eo
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    shortNames:
      - bucket
    singular: bucket
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                bucketName:
                  type: string
                secretName:
                  type: string
                secretNamespace:
                  type: string
                creationTimestamp:
                  type: string
