apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rm-bucket-operator
subjects:
- kind: ServiceAccount
  name: bucket-operator
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io