kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "login-service.fullname" .}}-cluster-rolebinding
subjects:
- kind: User
  name: system:serviceaccount:{{ .Values.global.namespace }}:{{ .Values.global.namespace }} # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole # this must be Role or ClusterRole
  name: {{ template "login-service.fullname" . }}-role # this must match the name of the ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Values.global.namespace }}
  name: gluu-config-role-binding-{{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.global.namespace }}
    name: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "login-service.fullname" . }}-role
  apiGroup: ""

