apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "config.fullname" . }}
spec:
  template:
    metadata:
      name: {{ template "login-service.name" . }}-job
      labels:
        app: {{ template "login-service.name" . }}-load
    spec:
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ include "config.fullname" . }}
        - name: {{ include "config.fullname" . }}-mount-gen-file
          configMap:
            name: {{ include "config.fullname" . }}-gen-json-file
        - name: {{ include "config.fullname" . }}-tls-script
          configMap:
            name: {{ include "config.fullname" . }}-tls-script
      containers:
      - name: {{ template "login-service.name" . }}-load
        image: gluufederation/config-init:4.1.1_02
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
          limits:
            memory: {{ .Values.limits.memory }}
            cpu: {{ .Values.limits.cpu }}
        volumeMounts:
          - mountPath: /opt/config-init/db/
            subPath: config-init/db
            name: vol-userman
          - mountPath: /opt/config-init/db/generate.json
            name: {{ include "config.fullname" . }}-mount-gen-file
            subPath: generate.json
          - mountPath: /scripts/tls_generator.py
            name: {{ include "config.fullname" . }}-tls-script
            subPath: tls_generator.py
        envFrom:
        - configMapRef:
            name: {{ include "config.fullname" . }}-config-cm
        command: ["/bin/sh", "-c"]
        args: ["tini -g -- /app/scripts/entrypoint.sh load && /usr/bin/python /scripts/tls_generator.py"]
      restartPolicy: Never
          