apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.configMapName | default (include "uma-user-agent.fullname" .) }}
data:
  config.yaml: |
    logging:
      level: {{ .Values.logging.level }}
    network:
      httpTimeout: {{ .Values.httpTimeout }}
      listenPort: {{ .Values.service.port }}
    pep:
      url: {{ printf "http://%s:%d/authorize" .Values.global.pep (index .Values "global" "ports" "proxy-pep" "port" | int) }}
    userIdCookieName: {{ .Values.userIdCookieName }}
    authRptCookieName: {{ printf "%s-%s" .Values.authRptCookieName .Values.global.context }}
    unauthorizedResponse: {{ .Values.unauthorizedResponse }}
    openAccess: {{ .Values.openAccess }}
