apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - jupyter.{{ .Values.hostname }}
      secretName: jupyter-tls
  rules:
  - host: jupyter.{{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jupyter
            port:
              number: {{ .Values.service.port }}
