nameOverride: ""
fullnameOverride: ""
kubeVersionOverride: ""
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  automountServiceAccountToken: false
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: false
    # fsGroup: 2000
  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # runAsUser: 1000
  extraArgs: []
  # - --foo
  # - --bar
  extraEnvVars: []
  # - name: FOO
  #   value: BAR
  extraVolumes: []
  # - emptyDir: {}
  #   name: tmp
  extraVolumeMounts: []
  # - mountPath: /tmp
  #   name: tmp
  priorityClassName: ""
  hostAliases: []
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"
  # - ip: "10.1.2.3"
  #   hostnames:
  #   - "foo.remote"
  #   - "bar.remote"
  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe:
    enabled: false
    httpGet:
      path: /oauth/health
      port: admin
  readinessProbe:
    enabled: true
    httpGet:
      path: /oauth/health
      port: admin
service:
  type: ClusterIP
  annotations: {}
  proxy:
    port: 3000
    nodePort:
  admin:
    port: 4000
    nodePort:
serviceAccount:
  create: true
  annotations: {}
  name: ""
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: identity.gatekeeper.demo.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: identity-gatekeeper-tls-certificate
      hosts:
        - identity.gatekeeper.demo.eoepca.org
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80
pdb:
  create: false
  minAvailable: 1
metrics:
  addPrometheusScrapeAnnotation: false
  serviceMonitor:
    enabled: false
    namespace: um
    additionalLabels: {}
    annotations: {}
    interval:
config:
  client-id: dummy-service
  discovery-url: https://identity.keycloak.demo.eoepca.org/realms/master
  no-redirects: true
  no-proxy: true
  enable-uma: true
  cookie-domain: demo.eoepca.org
  cookie-access-name: auth_user_id
  cookie-refresh-name: auth_refresh_token
  enable-metrics: true
  enable-logging: true
  enable-request-id: true
  enable-login-handler: true
  enable-refresh-tokens: true
  enable-logout-redirect: true
  listen: :3000
  listen-admin: :4000
secrets:
  clientSecret: AgBTtHR/dbA0ikvmydxqelvqwK2jHk5JBOuTfwUlQrvb9fBznQ8Ce/eb/RAr7s+fkP84RT1UIR0GdScAVfzl/aUl1ErgVudo49K8U/Kq5oWqRMMLBd2xJFlyeCPG7chLz/O7Z42MNFdzqn8eKlALVQg+cEh+Aeh8ey/kne8MUFkGEufDxgWwHO47RGTKoiLeyumQ8y8uxhDZNywvGq9/0TSsQoA8Pho5DBOCi6ocglgL7q1xBLfak36WmDfSxcmtXX2URYmS6UgZidDD0zoWgx/2aNNKalIBTy92ZcMD42oD153cuLDfbcfqs57+vpkzDSYZpwU6Pj50fGLmrGvuopWHk1YLbi9fXcoD087fkbBP2w3ur68eqphc+Pyf+/wgRRn2jwL8MGheyhsuLPECz1oHo0bhFVUmBOl8hNzujxz0a8yGO9+1H1RNySxFfoc5+Iah/cH/AoTtNO8/hxLuPM9CQVx1AV1TX6lmKG30yMjO8Sn8CR81leBmUaJuZdQm6tAf+vMQNFpK3Bz2uIViRmhr64ZxCe0Uljb7sPVowYxzr4Df8am4lRT82JvKXeWAaNOBeNMZIvZ7CcLfpomzTfbIV0aKyScJ4uJV4fdsr5PLP4CmJXusQi2ajzh/nqWD10E1LI6KEMVJH1lFCliLo/c4/F+o2hpK+wFG97Vl9y/Jd8E0JUUZ9n/bnFNkJAQLx9ehiioeCOsQqiBtV8bUBKpfnVgT4sVxJK0Dt16r6Ng+qw==
  encryptionKey: AgCpHHk8Oyhmkm4/4XKCXBMrlvV3gv2ngs6opNCP9vFVNoo1JO9VVF8ghipqJxjy6ao+hXWp6x+Hc0oumgl8BtwfSX1KBKQAEDHqImogSYdpkoCP5+CbUNN+Vqgg0NS7SLYd3HY8EJBuFp5Go/G9A0e/6WREo7hT2+CtF6qjg4Dt1fQamKLYDAX3tAKXi6KH0H5IaBskL/RK+ifGVIp2Q44I14XZYBkZ5gsQZPUMGYLFWuPlx+NOL8DXkmTN4Fvq5bGFytfPMW9ZllGkRMLPq8wvgiWhp9rghZKxd/QnLsjkOp5XmS2TnXXbuQTjmh07/Yt4ZdC2cRNsH5b5Rk+n2/MMT+XB/tqtqi67ooig3Rg1NmiuYqHVipywi7YU4VQO855Vmvx2T7hYo+XZQE/CJqIM9v1zUZySWfvATWZHQ3w2Z6eRRxbDRqIAnCI6bMVLCH+1vOeMGQ8bvNOqyr6YBpNQBYvDQfYgEgTTkjQwNNLmfRnfZygPF+NvbUQSkAuNY9uMl9Rj9ccrsf+cbIOuiukOZuleHVe3o4PSuk8VlCRaNTUpUc+lQutnCN20C9ZJLTmBVsho1FFiimnpmCSn7Vo90XAymOwyHW/qq390gB7Py+9OXdzhGJ70t5LTtdTX9ihbZjC1Id133TAqwoCWkEKDSHjmWOj8ElygXLnLDd1YIdyjpONbYuOU/GsPUsgs9E5F07bSfgvf1UaUNn4+OVqSh0W7zE+/yRkmOF3a9+lRLg==