nameOverride: ""
fullnameOverride: ""
kubeVersionOverride: ""
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  automountServiceAccountToken: false
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: false
    # fsGroup: 2000
  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # runAsUser: 1000
  extraArgs: []
  # - --foo
  # - --bar
  extraEnvVars: []
  # - name: FOO
  #   value: BAR
  extraVolumes: []
  # - emptyDir: {}
  #   name: tmp
  extraVolumeMounts: []
  # - mountPath: /tmp
  #   name: tmp
  priorityClassName: ""
  hostAliases: []
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"
  # - ip: "10.1.2.3"
  #   hostnames:
  #   - "foo.remote"
  #   - "bar.remote"
  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe:
    enabled: false
    httpGet:
      path: /oauth/health
      port: admin
  readinessProbe:
    enabled: true
    httpGet:
      path: /oauth/health
      port: admin
service:
  type: ClusterIP
  annotations: {}
  proxy:
    port: 3000
    nodePort:
  admin:
    port: 4000
    nodePort:
serviceAccount:
  create: true
  annotations: {}
  name: ""
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: identity.gatekeeper.demo.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: identity-gatekeeper-tls-certificate
      hosts:
        - identity.gatekeeper.demo.eoepca.org
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80
pdb:
  create: false
  minAvailable: 1
metrics:
  addPrometheusScrapeAnnotation: false
  serviceMonitor:
    enabled: false
    namespace: um
    additionalLabels: {}
    annotations: {}
    interval:
config:
  client-id: dummy-service
  discovery-url: https://identity.keycloak.demo.eoepca.org/realms/master
  no-redirects: true
  no-proxy: true
  enable-uma: true
  cookie-domain: demo.eoepca.org
  cookie-access-name: auth_user_id
  cookie-refresh-name: auth_refresh_token
  enable-metrics: true
  enable-logging: true
  enable-request-id: true
  enable-login-handler: true
  enable-refresh-tokens: true
  enable-logout-redirect: true
  listen: :3000
  listen-admin: :4000
secrets:
  clientSecret: AgCgx2NClwfguTB2OhNeA0+/DlvsvgbJq5pkpg+hp6hsY/wp1a8q9dpU67Gepdzw33rujxFQnQH/YpJrM+pWJ4knAkS5CjD88t2q0vgmbhBTgPwQFDb0xZc2trZ26Ne39cQqWdyVHXFO8BorduJIWTEKRR2z9KJ1OOfOqap+mERK0mex2RyCQZDlo3dtPiFy1ftTpE/cunE/xPZUyeHmIFzMP/a/Cv5Be82g6fECZcl4wTe2n+8UOnau5KfHX4xkId6HCjRVheOXn2M8YSSCfnznc2sOwmtQG03PhkcBtOTuNkUjUs0807HtuMG87Jir9HWBmKKz0XSrMfJQ2JH8pBVrlX6Bx9UUyO0oQpa/kCiFfWkW8iklxLZasrPLb/q0DVTVpjH8EvXlDiNo9/acy3G2Ue2syeWJ2OjhecRt2Ws48kqFuHK8GJZyIvjt+aCZ/wbr+v9sIIew9B/8rCt9M1d5RN0Tjr7xI0xoPqvvLWZ5Ij2LUpAX8rCH9sTNUsEF44uRI+KSZdhhmtYDnpvcle0rLN1TC8MgSsupAw6p7BIm+mmpuELz+h6dVBxRP7VPdW7r6I1nTPqO1qGgUWBd2WYITkPYpoRJ6TrrFW4dLihEqanN+gTx7oYfPXIrvn7PIzLBEqVBssvdHm6ItCvI6NnOCXyI2dTSIrf2EQEcSDaO76ZEqV4tlwBFeZpHW4PlS4lIOC/TshOiT4SV6wKKpI/II+JA8JIpqaO8TJX9DhV/HA==
  encryptionKey: AgCZXSn+WfaT2WLdZ590T4Xkz2ch9HZZavCyg94OqZjdrufn2zubpg7ZI6GbUvTYDXJMJIRhsJCkcPOlCfkVwT6zaJY+IWwCwLE1PrsrypG3FiIrHI9MJEgRkJ+HZKPG5BF+7uLyFVfrippEVghYkiMa5kaYrrA6+aH6PyfVSoWM0gR7elAOFLWivbrk8J8oLF1ZHKbqlCgkXITcN5YdMjUXOq4FwA7b6iGnh0YEVZTwFNCMNAatwnGtFxqTN0063qszjqj0VuyAAGpF3FsPvgRJPHtX+5rqENUhIw6ZqHAr0R+wPrRZyPYzsn4Br2yrel1FkO0uzjuc/AZgouEHbRD/9MilO+9ApsP7xJZaUdy73e5YmXR+8ufEtLNf9UOfnQAwt2SRd2qRFCPW4F9WsgmceK6bq+SLN89nI5LLgtGf+TP7KxlPEgfj7qrhgvtf1yOQowaTMT3hkaBfmMmzWZoviJMGnbM62Q0CLqQtKyGlLk8HQ4rV/bogi1g0zmP9DOxJiISYZ0Qqg03zAtIRHMyPUn+kznZWIF66GSnYkdtenPBJKFob6MurbSdAKpiC9TVITkeFGWAAwExmPXxGnFPK33iuxooHbsQ7Ds5fEtW/CaNsHImB/yrHYPsv4ze2O573PM4HDDC17jgT5IMs0gKOWprUKLcj2Df+AfsZz9SC25naDBCTbcu4SC//UNouq6n+CDZZR6rNf5STk8BubQT4I/sn6iDlyPL4CtTWncpnaA==