apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eoepca-portal.name" . }}
  labels:
    {{- include "eoepca-portal.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  CONFIGURATION: "{{ .Values.configmap.configuration }}"