{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.context }}-service-static
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls: 
  - secretName: "user-profile-tls-certificate"
    hosts:
      - {{ .Values.global.domain | quote }}
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: /static
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: "ImplementationSpecific"
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ .Values.global.user }}
            port:
              number: {{ .Values.global.servicePort }}
          {{- else }}
          serviceName: {{ .Values.global.user }}
          servicePort: {{ .Values.global.servicePort }}
          {{- end }}



---

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.context }}-service
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls: 
  - secretName: {{ printf "%s-user-profile-tls" .Values.context | quote }}
    hosts:
      - {{ .Values.global.domain | quote }}
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: {{ .Values.global.baseUri }}
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: "ImplementationSpecific"
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ .Values.global.user }}
            port:
              number: {{ .Values.global.servicePort }}
          {{- else }}
          serviceName: {{ .Values.global.user }}
          servicePort: {{ .Values.global.servicePort }}
          {{- end }}