apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.user }}
  labels:
    app: {{ .Values.global.user }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.user }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.user }}
    spec:
      containers:
      - name: {{ .Values.global.user }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        image: {{ .Values.image.image }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.global.servicePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.global.servicePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        ports:
        {{- range $key, $value := .Values.ports }}
        - containerPort: {{ $value.targetPort }}
          name: {{ $key }}
          protocol: {{ $value.type }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.global.user }}-cm
        volumeMounts:
        - mountPath: /opt/user-profile/db/um-user-profile-config
          subPath: um-user-profile-config
          name: config-user
          mountPropagation: HostToContainer
        - mountPath: /opt/gluu/jetty/user-profile/logs
          subPath: user-profile/logs
          name: {{ .Values.volumeClaim.name }}
      
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
        - name: {{ .Values.volumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: config-user
          configMap:
            name: {{ .Values.global.user }}-cm
