kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-access-db
  namespace: {{ .Values.global.namespace }}
  labels:
    k8s-app: data-access-user
    name: data-access-user
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
