{{- if .Values.secrets.adminPassword -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "identity-api.name" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  ADMIN_PASSWORD: "{{ .Values.secrets.adminPassword | b64enc }}"
{{- end }}