# Default values for pricing-engine.

global:
  namespace: default
  ep: test.10.0.2.15.nip.io
  domain:  https://test.10.0.2.15.nip.io
  pricing: pricing-engine
  auth_server_url: https://test.10.0.2.15.nip.io
  prefix: /
  host: 0.0.0.0
  port: 5570
  check_ssl_certs: "'false'"
  debug_mode: "'true'"
  nginxIp: 10.0.2.15



image: 
  statefulSetReplicas: 1
  imagePullPolicy: Always
  image: eoepca/um-pricing-engine:latest
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

config:
  enabled: true