{{ if .Values.iam.config.targetNamespace -}}
{{ if .Values.iam.config.propagateSecrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-provider
  namespace: {{ .Values.iam.config.targetNamespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: iam-secret-store
  target:
    name: keycloak-provider
  data:
    - secretKey: credentials
      remoteRef:
        key: keycloak-provider
        property: credentials
{{ end -}}
{{ end -}}
