{{ if .Values.iam.config.targetNamespace -}}
{{ if .Values.iam.config.propagateSecrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opa-route
  namespace: {{ .Values.iam.config.targetNamespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: iam-secret-store
  target:
    name: opa-route
  data:
    - secretKey: client_id
      remoteRef:
        key: opa-route
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: opa-route
        property: client_secret
{{ end -}}
{{ end -}}
