apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oxauth.fullname" . }}
  labels:
    app: {{ .Values.global.oxAuthServiceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.oxAuthServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.oxAuthServiceName }}
    spec:
      containers:
      - name: {{ template "login-service.fullname" . }}
        imagePullPolicy: {{ .Values.global.images.oxauth.pullPolicy }}
        image: eoepca/{{ .Values.global.images.oxauth.repository }}:{{ .Values.global.images.oxauth.tag }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "if [ -f /data/customizations_oxauth.tar.gz ]; then tar xvf /data/customizations_oxauth.tar.gz -C /opt/gluu/jetty/oxauth/; fi"]

        ports:
        - name: oxauth
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ template "oxauth.fullname" . }}-cm
        volumeMounts:
        {{- range $key, $value := .Values.volumeMounts }}
          - mountPath: {{ $value.mountPath }}
            name: vol-userman
            subPath: {{ $value.subPath }}
        {{- end }}
          - name: customizations
            mountPath: /data/
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: customizations
          configMap:
            name: front-customizations
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}