apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.oxAuthServiceName }}
  labels:
    app: {{ .Values.global.oxAuthServiceName }}
  {{- if .Values.global.elbId }}
  annotations: 
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: f4ba5972-e647-4715-9fb4-1e9926205fd3
  {{- end }}
spec:
  ports:
  - port: 8080
    name: oxauth
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.global.oxAuthServiceName }}
  {{- if .Values.elbIp }}
  type: NodePort
  {{- end }}
  {{- if .Values.global.elbId }}
  type: LoadBalancer
  {{- end }}