apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "oxtrust.fullname" . }}-ss
  labels:
    app: oxtrust
spec:
  serviceName: oxtrust
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oxtrust
  template:
    metadata:
      labels: 
        app: oxtrust
    spec:
      containers:
      - name: {{ include "oxtrust.name" . }}
        imagePullPolicy: {{ .Values.global.images.oxtrust.pullPolicy }}
        image: eoepca/{{ .Values.global.images.oxtrust.repository }}:{{ .Values.global.images.oxtrust.tag }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "if [ -f /data/customizations_oxtrust.tar.gz ]; then tar xvf /data/customizations_oxtrust.tar.gz -C /opt/gluu/jetty/identity/; fi"]
        
        ports:
        - containerPort: 8080
          name: oxtrust
          protocol: TCP
        env:
        - name: JVM_OPTS
          value: "-XshowSettings:vm -XX:MaxRAMPercentage=80"
        envFrom:
        - configMapRef:
            name: {{ template "oxtrust.fullname" . }}-cm

        volumeMounts:
        {{- range $key, $value := .Values.volumeMounts }}
          - mountPath: {{ $value.mountPath }}
            name: vol-userman
            subPath: {{ $value.subPath }}
        {{- end }}
          - name: customizations
            mountPath: /data/
        livenessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: customizations
          configMap:
            name: front-customizations
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}