apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendj.fullname" . }}
data:
  GLUU_CONFIG_ADAPTER: {{ .Values.opendj.configAdapter | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.opendj.configAdapter | quote }}
  GLUU_LDAP_INIT_HOST: {{ .Values.global.serviceName }} #{{ template "login-service.fullname" . }}-service
  GLUU_LDAP_ADVERTISE_ADRR: {{ .Values.opendj.add }}
  GLUU_LDAP_INIT: {{ .Values.gluuLdapInit | quote }}
  GLUU_LDAP_AUTO_REPLICATE: {{.Values.opendj.repLdap | quote}}
  GLUU_LDAP_INIT_PORT: {{ .Values.gluuLdapInitPort | quote }}
  GLUU_OXTRUST_CONFIG_GENERATION: {{ .Values.gluuOxtrustConfigGeneration | quote }}
  {{- if and (.Values.gluuRedisEnabled) (eq .Values.gluuCacheType "REDIS") }}
  GLUU_CACHE_TYPE: {{ .Values.gluuRedisCacheType | quote }}
  GLUU_REDIS_URL: {{ .Values.gluuRedisUrl | quote }}
  GLUU_REDIS_TYPE: {{ .Values.gluuRedisType | quote }}
  {{- else }}
  GLUU_CACHE_TYPE: {{ .Values.gluuCacheType | quote }}
  {{- end }}
  {{- if and (.Values.persistence.clientIDv) (.Values.persistence.clientSecretv) }}
  LP_CLIENT_ID: {{ .Values.persistence.clientIDv }}
  LP_CLIENT_SECRET: {{ .Values.persistence.clientSecretv }}
  {{- end }}
  {{- if and (.Values.persistence.coihClientIDv) (.Values.persistence.coihClientSecretv) }}
  COIH_CLIENT_ID: {{ .Values.persistence.coihClientIDv }}
  COIH_CLIENT_SECRET: {{ .Values.persistence.coihClientSecretv }}
  {{- end }}
  # must the same as the opendj service name
  GLUU_CERT_ALT_NAME: {{ .Values.global.serviceName }} #{{ template "login-service.fullname" . }}-service
  PDP_EP: {{ .Values.persistence.pdpEp | quote}}
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Values.global.namespace }}
  GLUU_SECRET_KUBERNETES_NAMESPACE: {{ .Values.global.namespace }}
  GLUU_NAMESPACE: {{ .Values.global.namespace }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-attributes-config  
data:
  {{ if .Files.Get "scripts/77-customAttributes.ldif" }}
  77-customAttributes.ldif: {{ .Files.Get "scripts/77-customAttributes.ldif" | quote  }}
  {{ else }}
  {{ fail "you need to supply your license file! add 'fs-license.conf' to your chart 'config' directory." }}
  {{ end }}