apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "login-service.fullname" . }}-init-ss
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.serviceName }} # has to match .spec.template.metadata.labels
  serviceName: {{ .Values.global.serviceName }}
  replicas: {{ .Values.statefulSetReplicas }} # by default is 1
  template:
    metadata:
      labels:
        app: {{ .Values.global.serviceName }} # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: config-attributes
          configMap:
            name: custom-attributes-config
      containers:
      - name: {{ template "login-service.fullname" . }}-init-container
        imagePullPolicy: {{ .Values.global.images.opendj.pullPolicy }}
        image: {{ .Values.global.images.opendj.repository }}:{{ .Values.global.images.opendj.tag }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /data/77-customAttributes.ldif /opt/opendj/template/config/schema/77-customAttributes.ldif"]
        envFrom:
        - configMapRef:
            name: {{ include "opendj.fullname" . }}
        ports:
        {{- range $key, $value := .Values.ports }}
          - containerPort: {{ $value.targetPort }}
            name: {{ $key }}
            protocol: TCP
        {{- end }}
        volumeMounts:
          - name: config-attributes
            mountPath: /data/
          - mountPath: /opt/opendj/config
            subPath: opendj/config
            name: vol-userman
          - mountPath: /opt/opendj/ldif
            subPath: opendj/ldif
            name: vol-userman
          - mountPath: /opt/opendj/logs
            subPath: opendj/logs
            name: vol-userman
          - mountPath: /opt/opendj/db
            subPath: opendj/db
            name: vol-userman
          - mountPath: /flag
            subPath: opendj/flag
            name: vol-userman
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}