apiVersion: v1
kind: ConfigMap
metadata:
  name: license-cm
data:
  LICENSE_REALM: {{ .Values.global.realm | quote }}
  LICENSE_AUTH_SERVER_URL: {{ .Values.global.domain | quote }}
  LICENSE_SERVICE_HOST: {{ .Values.global.serviceHost | quote }}
  LICENSE_SERVICE_PORT: {{ .Values.global.servicePort | quote }}
  LICENSE_S_MARGIN_RPT_VALID: {{ .Values.global.margin | quote }}
  LICENSE_CHECK_SSL_CERTS: {{ .Values.global.sslCerts | quote }}
  LICENSE_USE_THREADS: {{ .Values.global.useThreads | quote }}
  LICENSE_DEBUG_MODE: {{ .Values.global.debugMode | quote }}
  LICENSE_RESOURCE_SERVER_ENDPOINT: {{ .Values.global.resourceServer | quote }}
  LICENSE_API_RPT_UMA_VALIDATION: {{ .Values.global.umaValidation | quote }}
  LICENSE_RPT_LIMIT_USES: {{ .Values.global.limitUses | quote }}
  LICENSE_PDP_URL: {{ .Values.global.pdpUrl | quote }}
  LICENSE_PDP_PORT: {{ .Values.global.pdpPort | quote }}
  LICENSE_PDP_POLICY_ENDPOINT: {{ .Values.global.pdpPolicy | quote }}
  LICENSE_VERIFY_SIGNATURE: {{ .Values.global.verifySignature | quote }}
  LICENSE_PROXY_SERVICE_PORT: {{ .Values.global.proxyServicePort | quote }}
  LICENSE_RESOURCES_SERVICE_PORT: {{ .Values.global.resourcesServicePort | quote }}