apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.license }}
  labels:
    app: {{ .Values.global.license }}
spec:
  type: NodePort
  ports:
  - port: 5566
    name: http-license
    targetPort: 5566
    protocol: TCP
    nodePort: 31707
  - port: 1025
    name: https-license
    targetPort: 443
    protocol: TCP
  selector:
    app: {{ .Values.global.license }}
    